from whimsy.models import Job, Company, Skill, Task
import datetime

# Companies
company_mindtouch = Company(short_name="MindTouch", name="MindTouch Incorporated", link="http://www.mindtouch.com", location="San Diego, CA")
company_mindtouch.save()
company_rincon = Company(short_name="Rincon", name="Rincon Research Corporation", link="http://www.rincon.com", location="Tucson, AZ")
company_rincon.save()
company_ventana = Company(short_name="Ventana", name="Ventana Medical Systems", link="http://www.ventana.com", location="Oro Valley, AZ")
company_ventana.save()
company_ibm = Company(short_name="IBM", name="International Business Machines Corporation", link="http://www.ibm.com", location="Tucson, AZ")
company_ibm.save()
company_nmsu = Company(short_name="NMSU", name="New Mexico State University", link="http://www.nmsu.edu", location="Las Cruces, NM")
company_nmsu.save()

# Skills
skill_Python = Skill(name="Python", weight=10, link="http://www.python.org")
skill_Python.save()
skill_jQuery = Skill(name="jQuery", weight=10, link="http://jquery.com")
skill_jQuery.save()
skill_Django = Skill(name="Django", weight=9, link="https://www.djangoproject.com/")
skill_Django.save()
skill_JavaScript = Skill(name="JavaScript", weight=8, link="http://en.wikipedia.org/wiki/JavaScript")
skill_JavaScript.save()
skill_vim = Skill(name="vim", weight=8, link="http://www.vim.org/")
skill_vim.save()
skill_Firebug = Skill(name="Firebug", weight=8, link="https://getfirebug.com/whatisfirebug")
skill_Firebug.save()
skill_jQueryUI = Skill(name="jQueryUI", weight=6, link="http://jqueryui.com")
skill_jQueryUI.save()
skill_Bootstrap = Skill(name="Bootstrap", weight=6, link="http://twitter.github.io/bootstrap/")
skill_Bootstrap.save()
skill_Linux = Skill(name="Linux", weight=8, link="http://www.linux.org/")
skill_Linux.save()
skill_CSS3 = Skill(name="CSS3", weight=6, link="http://www.w3.org/TR/2001/WD-css3-roadmap-20010523")
skill_CSS3.save()
skill_HTML5 = Skill(name="HTML5", weight=6, link="http://www.w3.org/TR/html5")
skill_HTML5.save()
skill_JSON = Skill(name="JSON", weight=6, link="http://en.wikipedia.org/wiki/JSON")
skill_JSON.save()
skill_Sqlite = Skill(name="Sqlite", weight=6, link="http://www.sqlite.org/")
skill_Sqlite.save()
skill_XML = Skill(name="XML", weight=6, link="http://www.w3.org/XML/")
skill_XML.save()
skill_git = Skill(name="git", weight=6, link="http://git-scm.com/")
skill_git.save()
skill_RedHat = Skill(name="Red Hat", weight=5, link="http://www.redhat.com/")
skill_RedHat.save()
skill_Ubuntu = Skill(name="Ubuntu", weight=5, link="http://www.ubuntu.com/")
skill_Ubuntu.save()
skill_OpenLayers = Skill(name="Open Layers", weight=5, link="http://openlayers.org/")
skill_OpenLayers.save()
skill_PostgreSQL = Skill(name="PostgreSQL", weight=5, link="http://www.postgresql.org/")
skill_PostgreSQL.save()
skill_C = Skill(name="C", weight=5, link="http://en.wikipedia.org/wiki/C_%28programming_language%29")
skill_C.save()
skill_Cpp = Skill(name="Cpp", weight=5, link="https://en.wikipedia.org/wiki/C%2B%2B")
skill_Cpp.save()
skill_SVG = Skill(name="SVG", weight=5, link="http://www.w3.org/Graphics/SVG/")
skill_SVG.save()
skill_Office = Skill(name="Office", weight=5, link="http://office.microsoft.com/en-us/")
skill_Office.save()
skill_Cobbler = Skill(name="Cobbler", weight=4, link="http://www.cobblerd.org/")
skill_Cobbler.save()
skill_Windows = Skill(name="Windows", weight=5, link="http://windows.microsoft.com/en-us/windows/home")
skill_Windows.save()
skill_Underscore = Skill(name="Underscore", weight=5, link="http://underscorejs.org/")
skill_Underscore.save()
skill_MySQL = Skill(name="MySQL", weight=4, link="http://www.mysql.com/")
skill_MySQL.save()
skill_Mercurial = Skill(name="Mercurial", weight=4, link="http://mercurial.selenic.com/")
skill_Mercurial.save()
skill_Illustrator = Skill(name="Illustrator", weight=4, link="http://www.adobe.com/products/illustrator.html")
skill_Illustrator.save()
skill_Photoshop = Skill(name="Photoshop", weight=4, link="http://www.adobe.com/products/photoshop.html")
skill_Photoshop.save()
skill_IconFonts = Skill(name="Icon Fonts", weight=4, link="http://www.google.com/fonts/")
skill_IconFonts.save()
skill_Bash = Skill(name="Bash", weight=4, link="http://www.gnu.org/software/bash/")
skill_Bash.save()
skill_Csh = Skill(name="Csh", weight=4, link="http://en.wikipedia.org/wiki/C_shell")
skill_Csh.save()
skill_xMidas = Skill(name="xMidas", weight=4, link="http://www.rincon.com")
skill_xMidas.save()
skill_CSS = Skill(name="CSS", weight=4, link="http://www.w3.org/Style/CSS/Overview.en.html")
skill_CSS.save()
skill_HTML = Skill(name="HTML", weight=4, link="http://www.w3.org/html/")
skill_HTML.save()
skill_MongoDB = Skill(name="MongoDB", weight=3, link="http://www.mongodb.org/")
skill_MongoDB.save()
skill_suds = Skill(name="suds", weight=3, link="https://fedorahosted.org/suds/")
skill_suds.save()
skill_Zenoss = Skill(name="Zenoss", weight=3, link="http://community.zenoss.org/index.jspa")
skill_Zenoss.save()
skill_VB = Skill(name="VB for Apps", weight=3, link="http://en.wikipedia.org/wiki/Visual_Basic_for_Applications")
skill_VB.save()
skill_AIX = Skill(name="AIX", weight=3, link="http://en.wikipedia.org/wiki/IBM_AIX")
skill_AIX.save()
skill_LotusNotes = Skill(name="Lotus Notes", weight=3, link="http://www-03.ibm.com/software/products/us/en/ibmnotes")
skill_LotusNotes.save()
skill_Java = Skill(name="Java", weight=3, link="http://www.java.com/en/")
skill_Java.save()
skill_Delphi = Skill(name="Delphi", weight=3, link="http://www.embarcadero.com/products/delphi")
skill_Delphi.save()
skill_PHP = Skill(name="PHP", weight=3, link="http://us.php.net/")
skill_PHP.save()
skill_Perl = Skill(name="Perl", weight=3, link="http://www.perl.org/")
skill_Perl.save()
skill_Oracle = Skill(name="Oracle", weight=3, link="http://www.oracle.com/us/products/database/overview/index.html")
skill_Oracle.save()
skill_OSX = Skill(name="OSX", weight=4, link="http://www.apple.com/osx")
skill_OSX.save()
skill_CMVC = Skill(name="CMVC", weight=3, link="http://en.wikipedia.org/wiki/IBM_Configuration_Management_Version_Control_%28CMVC%29")
skill_CMVC.save()
skill_SVN = Skill(name="SVN", weight=3, link="http://subversion.apache.org/")
skill_SVN.save()

# Jobs

# Mindtouch

mt_task1 = Task(description="Senior Member of MindTouch’s small front end team, whose daily role is implementing fixes to a legacy codebase and surgically enhancing existing codebase with modern web advancements while also interfacing with Customer Success team to create new and exciting user experiences")
mt_task1.save()
mt_task2 = Task(description="Created a library of reusable widgets using jQueryUI’s Widget Factory Facade design pattern to allow for ease of maintenance and plug-and-play capabilities for 3rd party plugins")
mt_task2.save()

mt_job_1 = Job(company=company_mindtouch, title="Senior Software Engineer", short_title="Senior Engineer", department="User Experience", start=datetime.date(2013, 9, 16))
mt_job_1.save()
mt_job_1.tasks.add(mt_task1)
mt_job_1.tasks.add(mt_task2)
mt_job_1.skills.add(skill_jQuery)
mt_job_1.skills.add(skill_JavaScript)
mt_job_1.skills.add(skill_vim)
mt_job_1.skills.add(skill_Firebug)
mt_job_1.skills.add(skill_jQueryUI)
mt_job_1.skills.add(skill_CSS3)
mt_job_1.skills.add(skill_JSON)
mt_job_1.skills.add(skill_XML)
mt_job_1.skills.add(skill_OSX)
mt_job_1.skills.add(skill_HTML5)
mt_job_1.skills.add(skill_git)
mt_job_1.skills.add(skill_IconFonts)
mt_job_1.skills.add(skill_Bash)
mt_job_1.save()



# Rincon

rn_job_1 = Job(company=company_rincon, title="User Experience Engineer", short_title="UX Engineer", department="Integrated Solutions", start=datetime.date(2013, 1, 1), end=datetime.date(2013, 8, 31))
rn_job_1.save()

rn_task1 = Task(description="Designed and created a responsive web Front-End using advanced JavaScript techniques and leveraging Twitter's Bootstrap, jQuery, JSON through AJAX")
rn_task1.save()
rn_task2 = Task(description="Designed and created a responsive web Front-End, leveraging Bootstrap, jQuery and JSON for satellite downlink archiving software")
rn_task2.save()
rn_task3 = Task(description="Created and maintained a Kickstart repository for fast setup of machines at various global sites using Cobbler")
rn_task3.save()

rn_job_1.tasks.add(rn_task1)
rn_job_1.tasks.add(rn_task2)
rn_job_1.tasks.add(rn_task3)
rn_job_1.skills.add(skill_Python)
rn_job_1.skills.add(skill_jQuery)
rn_job_1.skills.add(skill_JavaScript)
rn_job_1.skills.add(skill_vim)
rn_job_1.skills.add(skill_Firebug)
rn_job_1.skills.add(skill_jQueryUI)
rn_job_1.skills.add(skill_Bootstrap)
rn_job_1.skills.add(skill_Linux)
rn_job_1.skills.add(skill_CSS)
rn_job_1.skills.add(skill_HTML)
rn_job_1.skills.add(skill_JSON)
rn_job_1.skills.add(skill_Sqlite)
rn_job_1.skills.add(skill_XML)
rn_job_1.skills.add(skill_RedHat)
rn_job_1.skills.add(skill_SVG)
rn_job_1.skills.add(skill_git)
rn_job_1.skills.add(skill_Cobbler)
rn_job_1.skills.add(skill_Illustrator)
rn_job_1.skills.add(skill_IconFonts)
rn_job_1.skills.add(skill_SVN)
rn_job_1.skills.add(skill_Bash)
rn_job_1.skills.add(skill_Csh)
rn_job_1.save()



rn_job_2 = Job(company=company_rincon, title="Full Stack Developer", short_title="Full Stack", department="Research & Technology", start=datetime.date(2011, 1, 1), end=datetime.date(2012, 12, 31))
rn_job_2.save()

rn_task4 = Task(description="Full stack development of several web applications: Implemented backend from the ground up, legacy database integration, and front end user interface utilizing Django, PostgreSQL/PostGIS, HTML/HTML5, CSS/CSS3, jQuery/jQuery UI") 
rn_task5 = Task(description="Designed and implemented several reusable jQuery UI Widget Factory plugins") 
rn_task6 = Task(description="Member of a team that maintained and enhanced an established multi-server cluster software framework written in Python and C++")

rn_task4.save() 
rn_task5.save() 
rn_task6.save() 

rn_job_2.tasks.add(rn_task4)
rn_job_2.tasks.add(rn_task5)
rn_job_2.tasks.add(rn_task6)

rn_job_2.skills.add(skill_Python)
rn_job_2.skills.add(skill_jQuery)
rn_job_2.skills.add(skill_Django)
rn_job_2.skills.add(skill_JavaScript)
rn_job_2.skills.add(skill_vim)
rn_job_2.skills.add(skill_Firebug)
rn_job_2.skills.add(skill_jQueryUI)
rn_job_2.skills.add(skill_Bootstrap)
rn_job_2.skills.add(skill_Linux)
rn_job_2.skills.add(skill_CSS)
rn_job_2.skills.add(skill_HTML)
rn_job_2.skills.add(skill_JSON)
rn_job_2.skills.add(skill_XML)
rn_job_2.skills.add(skill_RedHat)
rn_job_2.skills.add(skill_OpenLayers)
rn_job_2.skills.add(skill_PostgreSQL)
rn_job_2.skills.add(skill_Cpp)
rn_job_2.skills.add(skill_SVG)
rn_job_2.skills.add(skill_Mercurial)
rn_job_2.skills.add(skill_Illustrator)
rn_job_2.skills.add(skill_Photoshop)
rn_job_2.skills.add(skill_IconFonts)
rn_job_2.skills.add(skill_Bash)
rn_job_2.skills.add(skill_Csh)
rn_job_2.skills.add(skill_xMidas)
rn_job_2.skills.add(skill_MongoDB)
rn_job_2.skills.add(skill_suds)
rn_job_2.save()



rn_job_3 = Job(company=company_rincon, title="Software Engineer", short_title="Engineer", department="Applied Technology", start=datetime.date(2007, 9, 1), end=datetime.date(2010, 12, 31))
rn_job_3.save()

rn_task7 = Task(description="Team lead of a small team who conceived, analyzed, designed, implemented, tested, deployed, and maintained software-based solutions for modern geolocation systems in support of national security defense")
rn_task8 = Task(description="Aided in algorithm development, hardware control, GUI design, and database maintenance and development")
rn_task9 = Task(description="Productive member during 3 overseas trips, ending in successful deliveries")

rn_task7.save() 
rn_task8.save() 
rn_task9.save() 

rn_job_3.tasks.add(rn_task4)
rn_job_3.tasks.add(rn_task5)
rn_job_3.tasks.add(rn_task6)
rn_job_3.skills.add(skill_vim)
rn_job_3.skills.add(skill_Linux)
rn_job_3.skills.add(skill_HTML)
rn_job_3.skills.add(skill_RedHat)
rn_job_3.skills.add(skill_Cpp)
rn_job_3.skills.add(skill_Office)
rn_job_3.skills.add(skill_Windows)
rn_job_3.skills.add(skill_SVN)
rn_job_3.skills.add(skill_Bash)
rn_job_3.skills.add(skill_Java)
rn_job_3.skills.add(skill_PHP)
rn_job_3.skills.add(skill_Oracle)
rn_job_3.save()



vn_job = Job(company=company_ventana, title="Software Test Engineer", short_title="Test Engineer", department="Advanced Staining", start=datetime.date(2006, 7, 31), end=datetime.date(2007, 8, 31))
vn_job.save()

vn_task1 = Task(description="Authored, verified and executed system test plans and procedures for automated tissue staining instrument software under the strict regulations of the FDA’s General Principles of Software Validation")
vn_task2 = Task(description="Creation of automated Microsoft templates for generating a variety of test documents with VBA, including Test Plans, Test Protocols, Validation Summary Reports and Release Memos")
vn_task3 = Task(description="Creation and maintenance of collaborative team documentation through a Wiki web resource on a WIMP installation (Windows 2003, IIS, MySQL and PHP)")

vn_task1.save() 
vn_task2.save() 
vn_task3.save() 

vn_job.tasks.add(vn_task1)
vn_job.tasks.add(vn_task2)
vn_job.tasks.add(vn_task3)

vn_job.skills.add(skill_Office)
vn_job.skills.add(skill_Windows)
vn_job.skills.add(skill_VB)
vn_job.skills.add(skill_Delphi)
vn_job.save()



ibm_job1 = Job(company=company_ibm, title="Software Engineer", short_title="Engineer", department="Code Integration Test", start=datetime.date(2004, 6, 1), end=datetime.date(2005, 8, 31))
ibm_job1.save()

ibm_task1 = Task(description="Authored and executed DS-8000 ESS test plans for hardware/software integration functions for the Flexible Service Processor, pSeries Hypervisor and the xSeries Hardware Management Console")
ibm_task2 = Task(description="Served as the Tucson DS-8000 ESS Code Integration Test representative between product development/testing to San Jose, Austin, Rochester and Hungary sites")
ibm_task3 = Task(description="2 Bravo Awards for assignments at the manufacturing plant in Vac, Hungary")

ibm_task1.save() 
ibm_task2.save() 
ibm_task3.save() 

ibm_job1.tasks.add(ibm_task1)
ibm_job1.tasks.add(ibm_task2)
ibm_job1.tasks.add(ibm_task3)

ibm_job1.skills.add(skill_vim)
ibm_job1.skills.add(skill_AIX)
ibm_job1.skills.add(skill_Office)
ibm_job1.skills.add(skill_Windows)
ibm_job1.skills.add(skill_CMVC)
ibm_job1.skills.add(skill_LotusNotes)
ibm_job1.skills.add(skill_CMVC)
ibm_job1.skills.add(skill_Bash)
ibm_job1.skills.add(skill_Csh)
ibm_job1.skills.add(skill_Perl)
ibm_job1.save()



ibm_job2 = Job(company=company_ibm, title="Software Engineer", short_title="Engineer", department="Build Automation & Tools Team", start=datetime.date(2005, 9, 1), end=datetime.date(2006, 8, 1))
ibm_job2.save()

ibm_task4 = Task(description="Administered the IBM Configuration Management Version Control repository")
ibm_task5 = Task(description="Served as the team's focal point for the DS-8000 Enterprise Storage Subsystem while providing support to development, test and technical project leads for CMVC, DFS and GSA")
ibm_task6 = Task(description="Extended and automated a product build system used to package and deliver software")

ibm_task4.save() 
ibm_task5.save() 
ibm_task6.save() 

ibm_job2.tasks.add(ibm_task4)
ibm_job2.tasks.add(ibm_task5)
ibm_job2.tasks.add(ibm_task6)

ibm_job2.skills.add(skill_vim)
ibm_job2.skills.add(skill_AIX)
ibm_job2.skills.add(skill_Office)
ibm_job2.skills.add(skill_Windows)
ibm_job2.skills.add(skill_CMVC)
ibm_job2.skills.add(skill_LotusNotes)
ibm_job2.skills.add(skill_CMVC)
ibm_job2.skills.add(skill_Bash)
ibm_job2.skills.add(skill_Csh)
ibm_job2.skills.add(skill_Perl)
ibm_job2.save()



ibm_job3 = Job(company=company_ibm, title="Co-op / Early Verification Tester", short_title="Co-op", department="Baseline Team", start=datetime.date(2003, 1, 1), end=datetime.date(2003, 8, 31))
ibm_job3.save()

ibm_task7 = Task(description="Debugged and repaired hardware problems and Performed failure analysis")
ibm_task8 = Task(description="Tested hardware and software capabilities of the IBM 800 and F model Enterprise Storage Servers")

ibm_task7.save() 
ibm_task8.save() 

ibm_job3.tasks.add(ibm_task7)
ibm_job3.tasks.add(ibm_task8)

ibm_job3.skills.add(skill_vim)
ibm_job3.skills.add(skill_AIX)
ibm_job3.skills.add(skill_Office)
ibm_job3.skills.add(skill_Windows)
ibm_job3.skills.add(skill_CMVC)
ibm_job3.skills.add(skill_LotusNotes)
ibm_job3.skills.add(skill_CMVC)
ibm_job3.skills.add(skill_Bash)
ibm_job3.skills.add(skill_Csh)
ibm_job3.skills.add(skill_Perl)
ibm_job3.save()



nmsu_job1 = Job(company=company_nmsu, title="System Administrator", short_title="Sys Admin", department="Mathematics Department", start=datetime.date(2001, 8, 1), end=datetime.date(2002, 12, 31))
nmsu_job1.save()

nmsu_task1 = Task(description="Member of small team that administrated the Mathematics Department lab of 40+ computers and servers")
nmsu_task2 = Task(description="Troubleshot, repaired and installed hardware/software components")
nmsu_task3 = Task(description="Provided overall computer support for Department Professors and Graduate Students")

nmsu_task1.save() 
nmsu_task2.save() 
nmsu_task3.save() 

nmsu_job1.tasks.add(nmsu_task1)
nmsu_job1.tasks.add(nmsu_task2)
nmsu_job1.tasks.add(nmsu_task3)

nmsu_job1.skills.add(skill_vim)
nmsu_job1.skills.add(skill_Linux)
nmsu_job1.skills.add(skill_CSS)
nmsu_job1.skills.add(skill_HTML)
nmsu_job1.skills.add(skill_Office)
nmsu_job1.skills.add(skill_Windows)
nmsu_job1.skills.add(skill_Bash)
nmsu_job1.skills.add(skill_Csh)
nmsu_job1.save()



nmsu_job2 = Job(company=company_nmsu, title="System Administrator", short_title="Sys Admin", department="ICT", start=datetime.date(2003, 9, 1), end=datetime.date(2004, 5, 31))
nmsu_job2.save()

nmsu_task4 = Task(description="Packaged software and built system images for campus wide distribution")
nmsu_task5 = Task(description="Troubleshot, repaired and installed hardware/software components")

nmsu_task4.save() 
nmsu_task5.save() 

nmsu_job2.tasks.add(nmsu_task4)
nmsu_job2.tasks.add(nmsu_task5)

nmsu_job2.skills.add(skill_Office)
nmsu_job2.skills.add(skill_Windows)
nmsu_job2.save()
